_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "pretrained_weights/r50_300pro_3x_model.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "nnSyncBN"
  SparseRCNN:
    BOX_INIT_METHOD: "Image"
    NUM_PROPOSALS: 300
    NUM_CLASSES: 1
    NUM_HEADS: 6
    CLASS_WEIGHT: 2.0
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NOISE_VAR: 0.01
    USE_FOCAL: True
    USE_NMS: True
    NMS_THRESH: 0.9
    CRITERION_DYNAMIC: True
    OTA_K: 8
  FPN:
    NORM: "nnSyncBN"
DATASETS:
  TRAIN: ("icttd_opentables_train",)
  TEST:  ("icttd_opentables_val",)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (80000, )
  MAX_ITER: 96000
  CHECKPOINT_PERIOD: 8000
TEST:
  EVAL_PERIOD: 8000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "/data/logs/icttd_opentable_merged_300/"
